### ISSUE TITLE
Can't open jpegs

### ISSUE THREAD

**Issue by rohanag** [tzutalin/ImageNet_Utils#1]
The app works fine for me when I try to open a directory with .png  but I get nothing when opening a directory with jpegs. All jpeg's are filtered out here `if image.isNull():` in `loadFile` in `labelImg.py`

I have PyQt4 installed, on mac OS X 10.10.5, running on python 2.7.9.

Do you have any idea what might be going on? any suggestions?

Much Appreciated.

**Comment by tzutalin** [comment]
Any jpegs?  It's weird. Could you try to add log or print some messages in the bellow function.
https://github.com/tzutalin/labelImg/blob/a87ef4c70e31b468a58963c650bf1f39731bcaf0/labelImg.py#L750

**Comment by whcjb** [comment]
hello Lin，this app is very good. one question: the Next Image button and the Prev Image button can not work ,how to fix it?
Thanks

**Comment by tzutalin** [comment]
@whcjb, 
  Do you mean you load the images from a folders, and next and previous button cannot work? What's your OS?

**Comment by whcjb** [comment]
Yes, from a folder that have some images. My OS is Ubuntu 14.04-desktop

**Comment by whcjb** [comment]
Yes,from a folder that has many images. My OS is Ubuntu-14.04-desktop, nearly same to that in your demo video
