### ISSUE TITLE
Better examples

### ISSUE THREAD

**Issue by skerit** [tzutalin/ImageNet_Utils#2]
It's not totally clear how these utils are supposed to work.
I downloaded the "dog" images (n02084071) and its bounding box XMLs.

Afterwards I wanted to create the text files, like so:

```
./labelcreator.py --size_of_train 1400 --size_of_test 200 --label 11 --dir ./n02084071
```

But I got an error saying

```
IOError: cannot identify image file 'n02084071/n02084071_urlimages/lievendag1.jpg'
```

So what am I doing wrong here?

**Comment by tzutalin** [comment]
Hi @skerit ,
Could you pull it again and let me explain here

  Download the images according to the wnid,n02084071, from http://www.image-net.org/synset?wnid=n02084071 .
 `./downloadutils.py --downloadImages --wnid n02084071`

  It will create train.txt with the 1400 images and test.txt  with 200 images, and their label are 11.
  `./labelcreator.py --size_of_train 1400 --size_of_test 200 --label 11 --dir ./n02084071`

In the text file, the format will be like:

```
absolute_image_path1 11
absolute_image_path2 11
absolute_image_path3 11
absolute_image_path4 11
```

The format can be an input for DIGITS, Caffe, etc 
Does it sound to you?

Regards,
Tzutalin
