### ISSUE TITLE
automatically save xml

### ISSUE THREAD

**Issue by 201power** [tzutalin/ImageNet_Utils#3]
Hello Lin,

I am not familiar with python, do you know how can I change the code to automatically save xml with the format image_name.xml? 

Thanks!

**Comment by tzutalin** [comment]
@201power 
  What's your format? Would you like to dondate me to help you?

**Comment by 201power** [comment]
It's the same format as yours ...(ImageNet / VOC), i just want to change it to auto-save, so you don't have to click "save" button every image.

**Comment by tzutalin** [comment]
@201power, 
If you have set default save folder, the tool will save xml with the filename automatically while changing to the next image.

**Comment by 201power** [comment]
Great. Thanks!
