### ISSUE TITLE
much lesser number of annotated images as compared to total numer of images

### ISSUE THREAD

**Issue by agarwal-shubham** [tzutalin/ImageNet_Utils#5]
when i download annotations and images for say n03063968 (coffee-table which is also a leaf node), the number of annotated images are just 82 while the total number of images are 1597. If i split this data into train.txt and test.txt, then when i finally train my data i think it will run into errors as i don't have annotations for all files. Is there any workaround? or do we have to settle for less images (i.e. those which have annotations)

**Comment by tzutalin** [comment]
@agarwal-shubham 
If using ImageNet, it is possible to meet the number of annotation files is less than the number of the images. Could you add a workaround to check if the annotation of the image exists before training? E.g. Only train the images having annotated images

**Comment by agarwal-shubham** [comment]
@tzutalin 
Yeah, I did that, ran a script on data to extract only annotated images.
Thanks :)
